openapi: 3.0.0
info:
  title: CDE Transformer API
  version: 1.0.0
paths:
  /v1/files:
    get:
      summary: Get aggregated files from multiple CDE providers
      description: |
        Returns a unified file list from one or more CDE providers.
        Supports filtering by project ID.
      parameters:
        - name: providers
          in: query
          required: true
          schema:
            type: string
          description: Comma-separated list of providers
          example: bim360,procore
        - name: project
          in: query
          required: true
          schema:
            type: string
          description: Project ID to fetch files for
          example: 1234
      responses:
        "200":
          description: Unified file list
          content:
            application/json:
              example:
                - id: "file-1"
                  name: "Drawing A.pdf"
                  projectId: "1234"
                  provider: "bim360"
                - id: "file-2"
                  name: "Specs.docx"
                  projectId: "1234"
                  provider: "procore"
        "400":
          description: Missing providers or project ID
        "500":
          description: Server error
